version: "3.5"

services:
  db:
    env_file:
      - .env
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/database-init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db-data:/var/lib/mysql

  backend:
    container_name: spring-app
    build:
      context: .
      dockerfile: StockEasily-API/Dockerfile
    depends_on:
      - db
    command: sh -c "sleep 40 && java -jar -Dspring.profiles.active=prod /opt/app/StockEasily-API-0.0.1-SNAPSHOT.jar"
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: StockEasily-UI/DockerfileFrontend
    image: svelte
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db-data: